In [1]:
import pandas as pd
import numpy as np
import os

from sklearn.preprocessing import LabelEncoder

In [2]:
calm_path = r"2019_stress_detection_dataset\\CALM\\"
stress_path = r"2019_stress_detection_dataset\\STRESS\\"

## calm data

In [3]:
# calm files
calm_df = pd.DataFrame()

for i in range(1,111):
    for j in range(1, 8):
        file_path = calm_path + f"CALM_{i}_{j}.csv"
        try:
            if os.path.exists(file_path):
                df = pd.read_csv(file_path, sep=";",header=None)
                calm_df = pd.concat([calm_df, df], axis=0)
            else:
                print(f"File {file_path} does not exist.")
        except FileNotFoundError:
            print(f"File {file_path} not found.")

File 2019_stress_detection_dataset\\CALM\\CALM_1_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_1_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_2_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_2_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_3_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_3_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_4_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_4_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_5_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_5_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_6_5.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_6_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_6_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_7_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_7_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_8_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_8_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_9_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_9_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_10_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_10_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_11_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_11_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_12_2.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_12_5.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_12_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_12_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_13_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_13_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_14_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_14_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_15_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_15_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_16_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_16_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_17_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_17_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_18_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_18_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_19_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_19_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_20_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_20_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_21_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_21_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_22_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_22_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_23_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_23_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_24_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_24_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_25_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_25_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_26_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_26_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_27_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_27_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_28_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_28_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_29_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_29_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_30_5.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_30_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_30_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_31_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_31_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_32_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_32_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_33_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_33_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_34_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_34_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_35_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_35_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_36_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_36_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_37_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_37_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_38_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_38_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_39_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_39_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_40_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_40_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_41_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_42_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_42_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_43_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_43_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_44_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_44_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_45_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_45_7.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_46_6.csv does not exist.
File 2019_stress_detection_dataset\\CALM\\CALM_46_7.csv does not exist.

In [5]:
display(calm_df.isna().sum())

0          0
1          0
2          0
3          0
4          0
5          0
6          0
7          0
8          0
9          0
10         0
11         0
12         0
13         0
14         0
15         0
16         0
17         0
18         0
19         0
20         0
21         0
22         0
23         0
24         0
25         0
26         0
27         0
28         0
29         0
30         0
31         0
32         0
33         0
34         0
35         0
36         0
37         0
38         0
39         0
40         0
41         0
42         0
43         0
44    395165
45    395737
46    395165
dtype: int64

In [8]:
#calm_df_filtered = calm_df.iloc[:,2:].dropna(axis = 1)
calm_df_filtered = calm_df.dropna(axis = 1)

calm_df_filtered.drop(columns= [0], inplace = True)

display(calm_df_filtered)

C:\Users\sachl\AppData\Local\Temp\ipykernel_8072\2061031821.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  calm_df_filtered.drop(columns= [0], inplace = True)

,1,2,3,4,5,6,7,8,9,10,...,34,35,36,37,38,39,40,41,42,43
0,30,Male,1,0,1,27,-1.398295,4.552336,8.461134,9.709263,...,0.003678,-0.300669,0.918815,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0
1,30,Male,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,...,0.002873,-0.303881,0.919232,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0
2,30,Male,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.351746,-27.661564,-9.056985,45.024810,14.0
3,30,Male,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0
4,30,Male,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,21,Male,92,11,7,71,0.292102,6.706364,7.491686,10.059125,...,0.287248,0.745513,0.556130,0.000000,0.999999,253.035060,-43.073948,1.715667,256.680850,0.0
1176,21,Male,92,11,7,71,0.071828,6.775798,7.360001,10.004309,...,0.294343,0.744446,0.552979,0.000000,0.999999,252.861080,-43.928130,1.467874,256.652620,0.0
1177,21,Male,92,11,7,71,0.071828,6.775798,7.360001,10.004309,...,0.294343,0.744446,0.552979,0.000000,0.999999,252.861080,-43.928130,1.467874,256.652620,0.0
1178,21,Male,92,11,7,71,0.172388,7.101419,6.143709,9.391753,...,0.299511,0.744744,0.550441,0.000000,0.999999,252.706180,-44.326942,0.968044,256.566220,0.0
1179,21,Male,92,11,7,71,0.172388,7.101419,6.143709,9.391753,...,0.299511,0.744744,0.550441,0.000000,0.999999,252.706180,-44.326942,0.968044,256.566220,0.0

In [56]:
calm_df_filtered.drop_duplicates(inplace = True)
display(calm_df_filtered)

C:\Users\sachl\AppData\Local\Temp\ipykernel_8072\3200916711.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  calm_df_filtered.drop_duplicates(inplace = True)

,1,2,3,4,5,6,7,8,9,10,...,34,35,36,37,38,39,40,41,42,43
0,30,1,1,0,1,27,-1.398295,4.552336,8.461134,9.709263,...,0.003678,-0.300669,0.918815,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0
1,30,1,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,...,0.002873,-0.303881,0.919232,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0
2,30,1,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.351746,-27.661564,-9.056985,45.024810,14.0
3,30,1,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0
4,30,1,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1168,21,1,92,11,7,71,0.404632,6.591439,8.873182,11.060929,...,0.268713,0.746556,0.565016,0.000000,0.999999,253.620880,-41.065563,2.600405,256.937130,0.0
1172,21,1,92,11,7,71,-0.107742,6.890723,6.938608,9.779466,...,0.281774,0.745516,0.559193,0.000000,0.999999,253.278240,-42.488010,1.961180,256.824740,0.0
1174,21,1,92,11,7,71,0.292102,6.706364,7.491686,10.059125,...,0.287248,0.745513,0.556130,0.000000,0.999999,253.035060,-43.073948,1.715667,256.680850,0.0
1176,21,1,92,11,7,71,0.071828,6.775798,7.360001,10.004309,...,0.294343,0.744446,0.552979,0.000000,0.999999,252.861080,-43.928130,1.467874,256.652620,0.0
1178,21,1,92,11,7,71,0.172388,7.101419,6.143709,9.391753,...,0.299511,0.744744,0.550441,0.000000,0.999999,252.706180,-44.326942,0.968044,256.566220,0.0

In [10]:
label_enc = LabelEncoder()
calm_df_filtered[2] = label_enc.fit_transform(calm_df_filtered[2]).astype("int64")

C:\Users\sachl\AppData\Local\Temp\ipykernel_8072\3781898057.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  calm_df_filtered[2] = label_enc.fit_transform(calm_df_filtered[2]).astype("int64")

In [11]:
print("Classes and their corresponding codes:")
for class_, code in zip(label_enc.classes_, range(len(label_enc.classes_))):
    print(f"{class_}: {code}")

Classes and their corresponding codes:
Female: 0
Male: 1

In [47]:
# combining rows to reduce the rows
# combining 100 rows so 5 secs worth data in a single row
def combining_rows(df, row_count):
    #row_count = 100  # Change this value to control how many rows to stack horizontally

    # Calculate the number of rows to add
    num_rows_to_add = row_count - (len(df) % row_count)

    # Generate NaN values for the new rows
    new_rows_data = pd.DataFrame({col: [np.nan] * num_rows_to_add for col in df.columns})

    # Append the new rows to the DataFrame
    # this is to make the rows in the dataframe a multiple of the row_count
    calm_combine_df = pd.concat([df, new_rows_data], ignore_index=True)

    n = len(calm_combine_df)
    # Calculate the number of resulting columns
    num_columns = calm_combine_df.shape[1] * row_count

    # Reshape the DataFrame into desired shape
    reshaped_values = np.reshape(calm_combine_df.values, (-1, row_count, calm_combine_df.shape[1]))
    column_names = [f"{col}_{i}" for i in range(row_count) for col in calm_combine_df.columns]
    calm_combine_df = pd.DataFrame(reshaped_values.reshape(-1, num_columns), columns=column_names)

    return calm_combine_df

# (df, rowcount)
calm_combine_df = combining_rows(calm_df_filtered, 20) # 1 secs  1*20
#calm_combine_df = combining_rows(calm_df_filtered, 60) # 3 secs  3*20
#calm_combine_df = combining_rows(calm_df_filtered, 100) # 5 secs 5*20
#calm_combine_df = combining_rows(calm_df_filtered, 140) # 7 secs 7*20

In [57]:
#calm_combine_df.dropna(inplace = True)
#calm_combine_df["target"] = 0
#display(calm_combine_df)


calm_df_filtered["target"] = 0
display(calm_df_filtered)

C:\Users\sachl\AppData\Local\Temp\ipykernel_8072\571214419.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  calm_df_filtered["target"] = 0

,1,2,3,4,5,6,7,8,9,10,...,35,36,37,38,39,40,41,42,43,target
0,30,1,1,0,1,27,-1.398295,4.552336,8.461134,9.709263,...,-0.300669,0.918815,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0,0
1,30,1,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,...,-0.303881,0.919232,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0,0
2,30,1,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,...,-0.303881,0.919232,0.174533,1.015117,34.351746,-27.661564,-9.056985,45.024810,14.0,0
3,30,1,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,...,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0,0
4,30,1,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,...,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1168,21,1,92,11,7,71,0.404632,6.591439,8.873182,11.060929,...,0.746556,0.565016,0.000000,0.999999,253.620880,-41.065563,2.600405,256.937130,0.0,0
1172,21,1,92,11,7,71,-0.107742,6.890723,6.938608,9.779466,...,0.745516,0.559193,0.000000,0.999999,253.278240,-42.488010,1.961180,256.824740,0.0,0
1174,21,1,92,11,7,71,0.292102,6.706364,7.491686,10.059125,...,0.745513,0.556130,0.000000,0.999999,253.035060,-43.073948,1.715667,256.680850,0.0,0
1176,21,1,92,11,7,71,0.071828,6.775798,7.360001,10.004309,...,0.744446,0.552979,0.000000,0.999999,252.861080,-43.928130,1.467874,256.652620,0.0,0
1178,21,1,92,11,7,71,0.172388,7.101419,6.143709,9.391753,...,0.744744,0.550441,0.000000,0.999999,252.706180,-44.326942,0.968044,256.566220,0.0,0

In [58]:
#calm_combine_df.isna().sum().sum()

calm_df_filtered.isnull().sum().sum()

0

## stress data

In [15]:
# stress files
stress_df = pd.DataFrame()

for i in range(1,111):
    for j in range(1, 8):
        file_path = stress_path + f"STRESS_{i}_{j}.csv"
        try:
            if os.path.exists(file_path):
                df = pd.read_csv(file_path, sep = ";", header = None)
                stress_df = pd.concat([stress_df, df], axis=0)
            else:
                print(f"File {file_path} does not exist.")
        except FileNotFoundError:
            print(f"File {file_path} not found.")

File 2019_stress_detection_dataset\\STRESS\\STRESS_1_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_1_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_2_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_2_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_3_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_3_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_4_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_4_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_5_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_5_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_6_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_6_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_7_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_7_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_8_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_8_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_9_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_9_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_10_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_10_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_11_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_11_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_12_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_12_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_13_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_13_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_14_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_14_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_15_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_15_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_16_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_16_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_17_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_17_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_18_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_18_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_19_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_19_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_20_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_20_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_21_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_21_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_22_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_22_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_23_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_23_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_24_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_24_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_25_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_25_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_26_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_26_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_27_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_27_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_28_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_28_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_29_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_29_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_30_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_30_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_31_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_31_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_32_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_32_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_33_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_33_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_34_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_34_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_35_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_35_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_36_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_36_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_37_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_37_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_38_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_38_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_39_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_39_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_40_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_40_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_41_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_41_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_42_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_42_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_43_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_43_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_44_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_44_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_45_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_45_7.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_46_6.csv does not exist.
File 2019_stress_detection_dataset\\STRESS\\STRESS_46_7.csv does not exist.

In [17]:
display(stress_df.isna().sum())

0          0
1          0
2          0
3          0
4          0
5          0
6          0
7          0
8          0
9          0
10         0
11         0
12         0
13         0
14         0
15         0
16         0
17         0
18         0
19         0
20         0
21         0
22         0
23         0
24         0
25         0
26         0
27         0
28         0
29         0
30         0
31         0
32         0
33         0
34         0
35         0
36         0
37         0
38         0
39         0
40         0
41         0
42         0
43         0
44    331009
45    334339
46    331009
dtype: int64

In [18]:
#calm_df_filtered = calm_df.iloc[:,2:].dropna(axis = 1)
stress_df_filtered = stress_df.dropna(axis = 1)

stress_df_filtered.drop(columns= [0], inplace = True)

display(stress_df_filtered)

C:\Users\sachl\AppData\Local\Temp\ipykernel_8072\3103421590.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stress_df_filtered.drop(columns= [0], inplace = True)

,1,2,3,4,5,6,7,8,9,10,...,34,35,36,37,38,39,40,41,42,43
0,30,Male,1,0,1,27,-0.505169,4.584610,8.654279,9.806650,...,-0.018235,-0.291391,0.918954,0.174533,1.015117,33.315735,-30.103119,-6.949028,45.435944,14.0
1,30,Male,1,0,1,27,-0.505169,4.584610,8.654279,9.806650,...,-0.018235,-0.291391,0.918954,0.174533,1.015117,33.315735,-30.103119,-6.949028,45.435944,14.0
2,30,Male,1,0,1,27,-0.505169,4.584610,8.654279,9.806650,...,-0.018235,-0.291391,0.918954,0.174533,1.015117,36.269745,-27.845741,-2.123154,45.775402,14.0
3,30,Male,1,0,1,27,-0.315210,4.459319,8.487139,9.592518,...,-0.057790,-0.306295,0.920860,0.174533,1.015117,36.269745,-27.845741,-2.123154,45.775402,14.0
4,30,Male,1,0,1,27,-0.315210,4.459319,8.487139,9.592518,...,-0.057790,-0.306295,0.920860,0.174533,1.015117,36.269745,-27.845741,-2.123154,45.775402,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009,21,Male,74,4,7,67,0.114925,8.008849,5.528380,9.732310,...,0.307952,0.596749,0.658655,0.000000,0.999999,275.657600,-54.558193,-0.037395,281.004820,0.0
1010,21,Male,74,4,7,67,0.134079,8.157294,5.676825,9.939103,...,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0
1011,21,Male,74,4,7,67,0.134079,8.157294,5.676825,9.939103,...,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0
1012,21,Male,74,4,7,67,0.134079,8.157294,5.676825,9.939103,...,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0
1013,21,Male,74,4,7,67,0.134079,8.157294,5.676825,9.939103,...,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0

In [19]:
stress_df_filtered.drop_duplicates(inplace = True)
display(calm_df_filtered)

C:\Users\sachl\AppData\Local\Temp\ipykernel_8072\1164167508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stress_df_filtered.drop_duplicates(inplace = True)

,1,2,3,4,5,6,7,8,9,10,...,34,35,36,37,38,39,40,41,42,43
0,30,1,1,0,1,27,-1.398295,4.552336,8.461134,9.709263,...,0.003678,-0.300669,0.918815,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0
1,30,1,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,...,0.002873,-0.303881,0.919232,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0
2,30,1,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.351746,-27.661564,-9.056985,45.024810,14.0
3,30,1,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0
4,30,1,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1168,21,1,92,11,7,71,0.404632,6.591439,8.873182,11.060929,...,0.268713,0.746556,0.565016,0.000000,0.999999,253.620880,-41.065563,2.600405,256.937130,0.0
1172,21,1,92,11,7,71,-0.107742,6.890723,6.938608,9.779466,...,0.281774,0.745516,0.559193,0.000000,0.999999,253.278240,-42.488010,1.961180,256.824740,0.0
1174,21,1,92,11,7,71,0.292102,6.706364,7.491686,10.059125,...,0.287248,0.745513,0.556130,0.000000,0.999999,253.035060,-43.073948,1.715667,256.680850,0.0
1176,21,1,92,11,7,71,0.071828,6.775798,7.360001,10.004309,...,0.294343,0.744446,0.552979,0.000000,0.999999,252.861080,-43.928130,1.467874,256.652620,0.0
1178,21,1,92,11,7,71,0.172388,7.101419,6.143709,9.391753,...,0.299511,0.744744,0.550441,0.000000,0.999999,252.706180,-44.326942,0.968044,256.566220,0.0

In [20]:
#label_enc = LabelEncoder()
stress_df_filtered[2] = label_enc.transform(stress_df_filtered[2]).astype("int64")

C:\Users\sachl\AppData\Local\Temp\ipykernel_8072\2744508204.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stress_df_filtered[2] = label_enc.transform(stress_df_filtered[2]).astype("int64")

In [21]:
print("Classes and their corresponding codes:")
for class_, code in zip(label_enc.classes_, range(len(label_enc.classes_))):
    print(f"{class_}: {code}")

Classes and their corresponding codes:
Female: 0
Male: 1

In [50]:
# combining rows to reduce the rows
# combining 100 rows so 5 secs worth data in a single row
#def combining_stress_data(df, row_count):
    #row_count = 100  # Change this value to control how many rows to stack horizontally

    # Calculate the number of rows to add
#    num_rows_to_add = row_count - (len(df) % row_count)

    # Generate NaN values for the new rows
#    new_rows_data = pd.DataFrame({col: [np.nan] * num_rows_to_add for col in df.columns})

    # Append the new rows to the DataFrame
    # this is to make the rows in the dataframe a multiple of the row_count
#    stress_combine_df = pd.concat([df, new_rows_data], ignore_index=True)

#    n = len(stress_combine_df)
    # Calculate the number of resulting columns
#    num_columns = stress_combine_df.shape[1] * row_count

    # Reshape the DataFrame into desired shape
#    reshaped_values = np.reshape(stress_combine_df.values, (-1, row_count, stress_combine_df.shape[1]))

#    column_names = [f"{col}_{i}" for i in range(row_count) for col in stress_combine_df.columns]
#    stress_combine_df = pd.DataFrame(reshaped_values.reshape(-1, num_columns), columns=column_names)
#    return stress_combine_df


stress_combine_df = combining_rows(stress_df_filtered, 20) # 1secs  1*20
#stress_combine_df = combining_rows(stress_df_filtered, 60) # 3secs  3*20
#stress_combine_df = combining_rows(stress_df_filtered, 100) # 5secs  5*20
#stress_combine_df = combining_rows(stress_df_filtered, 140) # 7secs 7*20

In [59]:
#stress_combine_df.dropna(inplace = True)
#stress_combine_df["target"] = 1
#display(stress_combine_df)

stress_df_filtered["target"] = 1
display(stress_df_filtered)

C:\Users\sachl\AppData\Local\Temp\ipykernel_8072\3536719127.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stress_df_filtered["target"] = 1

,1,2,3,4,5,6,7,8,9,10,...,35,36,37,38,39,40,41,42,43,target
0,30,1,1,0,1,27,-0.505169,4.584610,8.654279,9.806650,...,-0.291391,0.918954,0.174533,1.015117,33.315735,-30.103119,-6.949028,45.435944,14.0,1
2,30,1,1,0,1,27,-0.505169,4.584610,8.654279,9.806650,...,-0.291391,0.918954,0.174533,1.015117,36.269745,-27.845741,-2.123154,45.775402,14.0,1
3,30,1,1,0,1,27,-0.315210,4.459319,8.487139,9.592518,...,-0.306295,0.920860,0.174533,1.015117,36.269745,-27.845741,-2.123154,45.775402,14.0,1
5,30,1,1,0,1,27,-0.319140,4.509158,8.581889,9.699648,...,-0.306295,0.920860,0.174533,1.015117,36.035430,-27.681293,-2.089430,45.488150,14.0,1
6,30,1,1,0,1,27,-0.319140,4.509158,8.581889,9.699648,...,-0.304428,0.921847,0.174533,1.015117,36.035430,-27.681293,-2.089430,45.488150,14.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,21,1,74,4,7,67,0.160416,8.095043,5.729500,9.918802,...,0.596268,0.659196,0.000000,0.999999,275.690160,-54.538303,0.160881,281.032960,0.0,1
1004,21,1,74,4,7,67,-0.217879,8.253065,5.925830,10.162481,...,0.596906,0.658894,0.000000,1.000000,275.679600,-54.487522,-0.091309,281.012700,0.0,1
1006,21,1,74,4,7,67,0.143656,8.028004,6.229903,10.162735,...,0.596855,0.659054,0.000000,0.999999,275.663570,-54.466236,0.023530,280.992830,0.0,1
1008,21,1,74,4,7,67,0.114925,8.008849,5.528380,9.732310,...,0.596749,0.658655,0.000000,0.999999,275.657600,-54.558193,-0.037395,281.004820,0.0,1
1010,21,1,74,4,7,67,0.134079,8.157294,5.676825,9.939103,...,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0,1

In [60]:
stress_df_filtered.isna().sum().sum()

0

# combining stress with calm df

In [61]:
combined_df = pd.concat([calm_df_filtered, stress_df_filtered], ignore_index = True, axis = 0)
display(combined_df)

#combined_1sec_df = pd.concat([calm_combine_df, stress_combine_df], ignore_index = True, axis = 0)
#display(combined_1sec_df)

#combined_3sec_df = pd.concat([calm_combine_df, stress_combine_df], ignore_index = True, axis = 0)
#display(combined_3sec_df)

#combined_5sec_df = pd.concat([calm_combine_df, stress_combine_df], ignore_index = True, axis = 0)
#display(combined_5sec_df)

#combined_7sec_df = pd.concat([calm_combine_df, stress_combine_df], ignore_index = True, axis = 0)
#display(combined_7sec_df)

#combined_raw_df = pd.concat([calm_df, stress_df], ignore_index = True, axis = 0)
#display(combined_raw_df)

,1,2,3,4,5,6,7,8,9,10,...,35,36,37,38,39,40,41,42,43,target
0,30,1,1,0,1,27,-1.398295,4.552336,8.461134,9.709263,...,-0.300669,0.918815,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0,0
1,30,1,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,...,-0.303881,0.919232,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0,0
2,30,1,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,...,-0.303881,0.919232,0.174533,1.015117,34.351746,-27.661564,-9.056985,45.024810,14.0,0
3,30,1,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,...,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0,0
4,30,1,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,...,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1279295,21,1,74,4,7,67,0.160416,8.095043,5.729500,9.918802,...,0.596268,0.659196,0.000000,0.999999,275.690160,-54.538303,0.160881,281.032960,0.0,1
1279296,21,1,74,4,7,67,-0.217879,8.253065,5.925830,10.162481,...,0.596906,0.658894,0.000000,1.000000,275.679600,-54.487522,-0.091309,281.012700,0.0,1
1279297,21,1,74,4,7,67,0.143656,8.028004,6.229903,10.162735,...,0.596855,0.659054,0.000000,0.999999,275.663570,-54.466236,0.023530,280.992830,0.0,1
1279298,21,1,74,4,7,67,0.114925,8.008849,5.528380,9.732310,...,0.596749,0.658655,0.000000,0.999999,275.657600,-54.558193,-0.037395,281.004820,0.0,1
1279299,21,1,74,4,7,67,0.134079,8.157294,5.676825,9.939103,...,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0,1

In [63]:
print(combined_df.isna().sum().sum())
combined_df.isnull().sum().sum()

0

0

In [64]:
combined_df.to_csv("combined.csv", index = False)

# task_wise split

In [15]:
column_names = [
    "participant_id", "age", "gender", "key_press_count", "delete_key_press_count", "text_id", 
    "text_length", "accelerometer_x", "accelerometer_y", "accelerometer_z", "accelerometer_magnitude",
    "gravity_x", "gravity_y", "gravity_z", "gravity_magnitude", "linear_acceleration_x", "linear_acceleration_y", 
    "linear_acceleration_z", "linear_acceleration_magnitude",
    "gyroscope_x", "gyroscope_y", "gyroscope_z", "gyroscope_magnitude", "magnetometer_x", 
    "magnetometer_y", "magnetometer_z", "magnetometer_magnitude", "light_sensor", "proximity_sensor",
    "game_rotation_vector_x", "game_rotation_vector_y", "game_rotation_vector_z", "game_rotation_vector_magnitude",
    "rotation_sensor_x", "rotation_sensor_y", "rotation_sensor_z", "rotation_sensor_scalar", "rotation_sensor_value",
    "rotation_sensor_magnitude", "orientation_azimuth", "orientation_pitch", "orientation_roll", "orientation_sensor_magnitude",
    "number_of_steps", "frame_touch_count", "participant_written_text", "text_to_be_written", "target"
]

combined_raw_df.columns = column_names
display(combined_raw_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1540372 entries, 0 to 1540371
Data columns (total 48 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   participant_id                  1540372 non-null  int64
 1   age                             1540372 non-null  int64
 2   gender                          1540372 non-null  object
 3   key_press_count                 1540372 non-null  int64
 4   delete_key_press_count          1540372 non-null  int64
 5   text_id                         1540372 non-null  int64
 6   text_length                     1540372 non-null  int64
 7   accelerometer_x                 1540372 non-null  float64
 8   accelerometer_y                 1540372 non-null  float64
 9   accelerometer_z                 1540372 non-null  float64
 10  accelerometer_magnitude         1540372 non-null  float64
 11  gravity_x                       1540372 non-null  float64
 12  gravity_y                       1540372 non-null  float64
 13  gravity_z                       1540372 non-null  float64
 14  gravity_magnitude               1540372 non-null  float64
 15  linear_acceleration_x           1540372 non-null  float64
 16  linear_acceleration_y           1540372 non-null  float64
 17  linear_acceleration_z           1540372 non-null  float64
 18  linear_acceleration_magnitude   1540372 non-null  float64
 19  gyroscope_x                     1540372 non-null  float64
 20  gyroscope_y                     1540372 non-null  float64
 21  gyroscope_z                     1540372 non-null  float64
 22  gyroscope_magnitude             1540372 non-null  float64
 23  magnetometer_x                  1540372 non-null  float64
 24  magnetometer_y                  1540372 non-null  float64
 25  magnetometer_z                  1540372 non-null  float64
 26  magnetometer_magnitude          1540372 non-null  float64
 27  light_sensor                    1540372 non-null  float64
 28  proximity_sensor                1540372 non-null  float64
 29  game_rotation_vector_x          1540372 non-null  float64
 30  game_rotation_vector_y          1540372 non-null  float64
 31  game_rotation_vector_z          1540372 non-null  float64
 32  game_rotation_vector_magnitude  1540372 non-null  float64
 33  rotation_sensor_x               1540372 non-null  float64
 34  rotation_sensor_y               1540372 non-null  float64
 35  rotation_sensor_z               1540372 non-null  float64
 36  rotation_sensor_scalar          1540372 non-null  float64
 37  rotation_sensor_value           1540372 non-null  float64
 38  rotation_sensor_magnitude       1540372 non-null  float64
 39  orientation_azimuth             1540372 non-null  float64
 40  orientation_pitch               1540372 non-null  float64
 41  orientation_roll                1540372 non-null  float64
 42  orientation_sensor_magnitude    1540372 non-null  float64
 43  number_of_steps                 1540372 non-null  float64
 44  frame_touch_count               814198 non-null   float64
 45  participant_written_text        810296 non-null   object
 46  text_to_be_written              814198 non-null   object
 47  target                          1540372 non-null  int64
dtypes: float64(38), int64(7), object(3)
memory usage: 564.1+ MB

None

In [19]:
combined_raw_df.to_csv("combined_raw.csv", index = False)

In [20]:
# reading csv back 

temp = pd.read_csv("combined_raw.csv")
display(temp)

C:\Users\sachl\AppData\Local\Temp\ipykernel_10368\4268834412.py:3: DtypeWarning: Columns (45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv("combined_raw.csv")

,participant_id,age,gender,key_press_count,delete_key_press_count,text_id,text_length,accelerometer_x,accelerometer_y,accelerometer_z,...,rotation_sensor_magnitude,orientation_azimuth,orientation_pitch,orientation_roll,orientation_sensor_magnitude,number_of_steps,frame_touch_count,participant_written_text,text_to_be_written,target
0,1,30,Male,1,0,1,27,-1.398295,4.552336,8.461134,...,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0,NaN,NaN,NaN,0
1,1,30,Male,1,0,1,27,-1.593871,4.467315,8.753821,...,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0,NaN,NaN,NaN,0
2,1,30,Male,1,0,1,27,-1.593871,4.467315,8.753821,...,1.015117,34.351746,-27.661564,-9.056985,45.024810,14.0,NaN,NaN,NaN,0
3,1,30,Male,2,0,1,27,-1.669115,4.492037,8.941505,...,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0,NaN,NaN,NaN,0
4,1,30,Male,2,0,1,27,-1.669115,4.492037,8.941505,...,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1540367,110,21,Male,74,4,7,67,0.114925,8.008849,5.528380,...,0.999999,275.657600,-54.558193,-0.037395,281.004820,0.0,0.0,"Yeryüzü boşaldı, habersiz miyiz? Güneşe göç va...","Yeryüzü boşaldı, habersiz miyiz? Güneşe göç va...",1
1540368,110,21,Male,74,4,7,67,0.134079,8.157294,5.676825,...,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0,0.0,"Yeryüzü boşaldı, habersiz miyiz? Güneşe göç va...","Yeryüzü boşaldı, habersiz miyiz? Güneşe göç va...",1
1540369,110,21,Male,74,4,7,67,0.134079,8.157294,5.676825,...,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0,0.0,"Yeryüzü boşaldı, habersiz miyiz? Güneşe göç va...","Yeryüzü boşaldı, habersiz miyiz? Güneşe göç va...",1
1540370,110,21,Male,74,4,7,67,0.134079,8.157294,5.676825,...,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0,0.0,"Yeryüzü boşaldı, habersiz miyiz? Güneşe göç va...","Yeryüzü boşaldı, habersiz miyiz? Güneşe göç va...",1
1540371,110,21,Male,74,4,7,67,0.134079,8.157294,5.676825,...,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0,0.0,"Yeryüzü boşaldı, habersiz miyiz? Güneşe göç va...","Yeryüzü boşaldı, habersiz miyiz? Güneşe göç va...",1

In [34]:
participant_df = temp["participant_id"].value_counts().sort_index().reset_index()
text_df = temp["text_id"].value_counts().sort_index().reset_index()

display(participant_df)
display(text_df)

     participant_id  count
0                 1  14870
1                 2  20476
2                 3  18726
3                 4  21622
4                 5  14753
..              ...    ...
105             106  20333
106             107   9307
107             108   6288
108             109  15778
109             110  17388

[110 rows x 2 columns]

   text_id   count
0        1  138448
1        2  181192
2        3  285410
3        4  407046
4        5  264539
5        6  168846
6        7   94891

# extra code

In [65]:
path = r"combined.csv"
path1 = r"combined_1sec.csv"
path3 = r"combined_3sec.csv"
path5 = r"combined_5sec.csv"
path7 = r"combined_7sec.csv"

df0 = pd.read_csv(path)
df1 = pd.read_csv(path1)
df3 = pd.read_csv(path3)
df5 = pd.read_csv(path5)
df7 = pd.read_csv(path7)

datasets = [df0, df1, df3, df5, df7]

shapes = pd.DataFrame({
    "DataFrame": ["original", "1 sec", "3 secs", "5 secs", "7 secs"],
    "Shape": [df0.shape, df1.shape, df3.shape, df5.shape, df7.shape],
    "Total Elements": [df0.shape[0] * df0.shape[1], df1.shape[0] * df1.shape[1], 
                       df3.shape[0] * df3.shape[1], df5.shape[0] * df5.shape[1], 
                       df7.shape[0] * df7.shape[1]]
})

display(shapes)

  DataFrame          Shape  Total Elements
0  original  (1279300, 44)        56289200
1     1 sec   (63964, 861)        55073004
2    3 secs  (21321, 2581)        55029501
3    5 secs  (12792, 4301)        55018392
4    7 secs   (9137, 6021)        55013877

In [64]:
# original
calm_df_filtered["target"] = 0
stress_df_filtered["target"] = 1
combined_df = pd.concat([calm_df_filtered, stress_df_filtered], ignore_index = True, axis = 0)
display(combined_df)
combined_df.to_csv("combined.csv", index = False)

,2,3,4,5,6,7,8,9,10,11,...,35,36,37,38,39,40,41,42,43,target
0,1,1,0,1,27,-1.398295,4.552336,8.461134,9.709263,-1.573943,...,-0.300669,0.918815,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0,0
1,1,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,-1.543731,...,-0.303881,0.919232,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,14.0,0
2,1,1,0,1,27,-1.593871,4.467315,8.753821,9.956240,-1.543731,...,-0.303881,0.919232,0.174533,1.015117,34.351746,-27.661564,-9.056985,45.024810,14.0,0
3,1,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,-1.528073,...,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0,0
4,1,2,0,1,27,-1.669115,4.492037,8.941505,10.144695,-1.528073,...,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,14.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1540367,1,74,4,7,67,0.114925,8.008849,5.528380,9.732310,-0.005215,...,0.596749,0.658655,0.000000,0.999999,275.657600,-54.558193,-0.037395,281.004820,0.0,1
1540368,1,74,4,7,67,0.134079,8.157294,5.676825,9.939103,0.011862,...,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0,1
1540369,1,74,4,7,67,0.134079,8.157294,5.676825,9.939103,0.011862,...,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0,1
1540370,1,74,4,7,67,0.134079,8.157294,5.676825,9.939103,0.011862,...,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0,1
1540371,1,74,4,7,67,0.134079,8.157294,5.676825,9.939103,0.011862,...,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,0.0,1